# Generated by Django 4.0.4 on 2022-11-22 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_alter_paciente_id_alter_questionario_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='questionario',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
